### ISSUE TITLE
program  !

### ISSUE THREAD

**Issue by Mehrdoost** [jeffbuffs/Waytime#2]
HI,

I think the program has a problem , The output it gives is as follows:

//www.QQQQQQQQQ.org/1999/xlink
/wp-includes/

// OR /  is before every word , That is correct ?

**Comment by jeffbuffs** [comment]
Dear @MehrshadMohammadi ,

I hope this message finds you well and that you are successfully earning income. As per your previous message, you have reported encountering the strings "/wp-inclused" and "//[www.QQQQ.org/1999/xlink](http://www.qqqq.org/1999/xlink)". These strings are being extracted by the tool using regular expressions to gather data. However, this data appears to be present in the robots.txt file of your target. As a result, the tool is extracting this information from the robots.txt file rather than the intended target.

Best regards,
@jeffbuffs
